### ISSUE TITLE
errors in different pipeline steps

### ISSUE THREAD

**Issue by egenomics** [mouliere-lab/ITSFASTR#1]
Hi,
I am trying to use the ITSFASTR workflow to process some cfDNA experiments. Right now I am just executing some control samples to see the output from the different steps but I fail to run all the different workflows.

I can execute trimming.smk, mapping.smk without problems once I have modified the .yaml and the samplesheet.csv, however the module ichorCNA.smk already fails.
The error I obtain is:
(snakemake) jlvillanueva@HCP14035:/playground/soft/ITSFASTR/workflow/rules/4_FrEIA$ cd ../2_copy_number_analysis

```
snakemake --printshellcmds \
          --keep-going \
          --use-conda \
          --cores $cores \
          -s ichorCNA.smk

/playground/soft/ITSFASTR/workflow/rules/2_copy_number_analysis/ichorCNA.smk:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  if config["Trimmer"] in ["bbduk", "cutadapt"]:
KeyError in file /playground/soft/ITSFASTR/workflow/rules/2_copy_number_analysis/ichorCNA.smk, line 22:
'conda_dir'
  File "/playground/soft/ITSFASTR/workflow/rules/2_copy_number_analysis/ichorCNA.smk", line 22, in <module>
```

The next module (fragmentation.smk) runs without problems and then module 4 (freia) fails again at the preprocessing step:

```
(snakemake) jlvillanueva@HCP14035:/playground/soft/ITSFASTR/workflow/rules/2_copy_number_analysis$ cd ../4_FrEIA

#Extract the fragment ends by running:

snakemake --printshellcmds \
          --keep-going \
          --use-conda \
          --cores $cores \
          -s preprocessing.smk
/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/preprocessing.smk:7: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  # Select output path depending on run mode.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                  count
-----------------  -------
FragmEndSeq              4
all_preprocessing        1
total                    5

Select jobs to execute...
Execute 1 jobs...

[Mon Apr 15 15:50:35 2024]
localrule FragmEndSeq:
    input: /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1810_S31_L001.bam
    output: /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.pq
    log: /corebm/tmp/cnag_tollagu/test_claret/results/logs/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.log
    jobid: 3
    benchmark: /corebm/tmp/cnag_tollagu/test_claret/results/benchmark/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.tsv
    reason: Missing output files: /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.pq
    wildcards: sample=SR1810_S31_L001
    threads: 24
    resources: tmpdir=/tmp


        python3 ../../scripts/4_FrEIA/1_extract_fragment_ends.py         -b /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1810_S31_L001.bam         -o /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.pq         -c chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrM         -t 24         -n 10         -m Illumina         2> /corebm/tmp/cnag_tollagu/test_claret/results/logs/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.log
        
Activating conda environment: .snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_
[Mon Apr 15 15:51:21 2024]
Error in rule FragmEndSeq:
    jobid: 3
    input: /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1810_S31_L001.bam
    output: /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.pq
    log: /corebm/tmp/cnag_tollagu/test_claret/results/logs/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.log (check log file(s) for error details)
    conda-env: /playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_
    shell:
        
        python3 ../../scripts/4_FrEIA/1_extract_fragment_ends.py         -b /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1810_S31_L001.bam         -o /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.pq         -c chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrM         -t 24         -n 10         -m Illumina         2> /corebm/tmp/cnag_tollagu/test_claret/results/logs/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

```

**Comment by moldovannorbert** [comment]
Dear @egenomics,
Thank you for your feedback.

The error of the ichorCNA.smk happens because of a missing line in the config file. I updated the config.yaml to fix this. You will find a new `conda_dir` parameter in the ICHORCNA CORE section. The location of the ichorCNA R script needs to be set in the config file. This is a behavior inherited from the original ichorCNA code. To do this, please run ichorCNA.smk with  `--conda-create-envs-only`. This will create the environment as well as telling you the path to it (something similar to `.snakemake/conda/103fe64931ac3076f3305793328dd331_` for example). Paste this path after `conda_dir` and run your code. Please also notice that I updated the r-ichorcna version to 0.3.2-2 in the subsequent code in the updated config.yaml.
Can you please report if this solved this part of the issue?

For FrEIA can you please share the contents of this file:  `/corebm/tmp/cnag_tollagu/test_claret/results/logs/testclaret/trimmed/4_FrEIA/1_extract_fragment_ends/SR1810_S31_L001.log`.

**Comment by egenomics** [comment]
Hi @moldovannorbert ,
Indeed your changes worked and I managed to run ichorCNA. Thanks!!

As for FrEIA I am attaching the log file that you requested:
```

/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/fastparquet/encoding.py:66: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @numba.jit(nogil=True)
/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/fastparquet/writer.py:70: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  pd.BooleanDtype(): np.bool
Traceback (most recent call last):
  File "../../scripts/4_FrEIA/1_extract_fragment_ends.py", line 190, in <module>
    Main()
  File "../../scripts/4_FrEIA/1_extract_fragment_ends.py", line 183, in Main
    OutDf.to_parquet(args.output,  # Save the results.
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/core/frame.py", line 2455, in to_parquet
    return to_parquet(
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/io/parquet.py", line 386, in to_parquet
    impl = get_engine(engine)
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/io/parquet.py", line 32, in get_engine
    return engine_class()
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/io/parquet.py", line 233, in __init__
    fastparquet = import_optional_dependency(
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/pandas/compat/_optional.py", line 106, in import_optional_dependency
    module = importlib.import_module(name)
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/fastparquet/__init__.py", line 6, in <module>
    from .writer import write
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/fastparquet/writer.py", line 70, in <module>
    pd.BooleanDtype(): np.bool
  File "/playground/soft/ITSFASTR/workflow/rules/4_FrEIA/.snakemake/conda/00ca78bdc0bda61970d6a506e3da839c_/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


```

**Comment by moldovannorbert** [comment]
Dear @egenomics,

Thanks for your feedback. The FrEIA bug happened because a weird incompatibility in the environment. In the updated `FrEIA_env.yaml` I upgraded `fastparquet` to v0.8.3 to fix this. 
During testing the code I found and fixed another bug in FrEIA.smk, so please make sure you update that too.

If this resolved your issue please close this ticket.

**Comment by egenomics** [comment]
Hi Norbert,
Thanks again for your help. I think you fixed the bug, as FrEIA is now running and generating some output. However, inside the results folder I am missing the folder number 5 that should contain the FrEIA scores, as detailed in the FrEIA github.:

└── 5_FrEIA_score/

The only folders I see are:
1_extract_fragment_ends
3_Abundances
4_Compare

A similar scenario is found for Griffin (error at the end), where I am not finding folders with the sample names, as is expected according to the example output data, where corrected coverages inside each sample folder are found or a folder with "plots"
![image](https://github.com/mouliere-lab/ITSFASTR/assets/3185205/c55c1819-4b1c-4a8c-853d-72a1ad5a268f)

Best,
JL

The error code from Griffin:
```
parameters:
	sample_name = "SR1811_S32_L001"
	bam_path = "/corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1811_S32_L001.bam"
	GC_bias_path = "/corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR/GC_bias/SR1811_S32_L001.GC_bias.txt"
	mappability_bias_path = "none"
	tmp_dir = "/corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed"
	ref_seq_path = "/corebm/seq/references/genomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta"
	mappability_bw = "../../../resources/Griffin_LR/k100.Umap.MultiTrackMappability.bw"
	chrom_sizes_path = "../../../resources/Griffin_LR/hg38.standard.chrom.sizes"
	sites_yaml = "/playground/soft/ITSFASTR/config/config.yaml"
	griffin_scripts_dir = "../../scripts/5_Griffin_LR"
	chrom_column = "Chrom"
	position_column = "position"
	strand_column = "Strand"
	chroms =  ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22']
	norm_window =  [-5000, 5000]
	sz_range = [100, 500]
	map_q = 5
	number_of_sites = "none"
	sort_by = "none"
	ascending = "none"
	CPU = 8


Skipping mappability correction
{'TssA': None, 'Quies': None}
Traceback (most recent call last):
  File "../../scripts/5_Griffin_LR/griffin_coverage.py", line 296, in <module>
    current_sites = griffin_functions.import_and_filter_sites(site_name,site_file,strand_column,chrom_column,position_column,chroms,ascending,sort_by,number_of_sites)
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/../../scripts/5_Griffin_LR/griffin_functions.py", line 9, in import_and_filter_sites
    current_sites = pd.read_csv(site_file,sep='\t')
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/common.py", line 558, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/site-packages/pandas/io/common.py", line 371, in _get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'NoneType'>

real	0m1,366s
user	0m0,982s
sys	0m0,962s
[Mon Apr 22 10:51:39 2024]
Error in rule calc_cov:
    jobid: 8
    input: /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1811_S32_L001.bam, /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR/GC_bias/SR1811_S32_L001.GC_bias.txt
    output: /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/SR1811_S32_L001/tmp_bigWig/SR1811_S32_L001.uncorrected.bw, /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/SR1811_S32_L001/tmp_bigWig/SR1811_S32_L001.GC_corrected.bw, /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/SR1811_S32_L001/tmp_pybedtools
    conda-env: /playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_
    shell:
        
		time ../../scripts/5_Griffin_LR/griffin_coverage.py 		--sample_name SR1811_S32_L001 		--bam /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/2_filter_and_index/SR1811_S32_L001.bam 		--GC_bias /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR/GC_bias/SR1811_S32_L001.GC_bias.txt 		--mappability_bias none 		--mappability_correction False 		--tmp_dir /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed 		--reference_genome /corebm/seq/references/genomes/igenomes/Homo_sapiens/GATK/GRCh38/Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta 		--mappability_bw ../../../resources/Griffin_LR/k100.Umap.MultiTrackMappability.bw 		--chrom_sizes_path ../../../resources/Griffin_LR/hg38.standard.chrom.sizes 		--sites_yaml ../../../config/config.yaml 		--griffin_scripts ../../scripts/5_Griffin_LR 		--chrom_column Chrom 		--position_column position 		--strand_column Strand 		--chroms chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 		--norm_window -5000 5000 		--size_range 100 500 		--map_quality 5 		--number_of_sites none 		--sort_by none 		--ascending none 		--CPU 8
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job calc_cov since they might be corrupted:
/corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/SR1811_S32_L001/tmp_pybedtools
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-04-22T105128.154421.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Comment by moldovannorbert** [comment]
Dear @egenomics,

Thanks for the further reports!

1. FrEIA score calculation: The ITSFASTR pipeline is not computing the FrEIA score thus it doesn't contain the code. It is relatively easy to implement it, however in the long run. If you wish this to be added, please create a separate issue with a feature request. In the meantime I would recommend to use the code from the FrEIA Github to compute it. The output of ITSFASTR should be compatible with FrEIA.

2. Griffin_LR missing outputs: Can you please show the contents of your config file under the **GRIFFIN_LR NUCLEOSOME PROFILING** section?

**Comment by egenomics** [comment]
Thanks for the answer!
About Griffin_LR, here it goes:
```
################################################################################
#################### GRIFFIN_LR NUCLEOSOME PROFILING ###########################
################################################################################
# Path to the mappability file.
mappability_bw: ../../../resources/Griffin_LR/k100.Umap.MultiTrackMappability.bw
# Path to chromosome sizes file.
chrom_sizes_path: ../../../resources/Griffin_LR/hg38.standard.chrom.sizes
# List of paths to the sites of interest files.
site_lists:
 TssA:
 Quies:
# Column containing the chromosome in your sites of interest file.
chrom_column: Chrom
# Column containing the site position.
position_column: position
# Column for indicating site direction. If this column doesn't exist, the script will assume non-directional sites.
strand_column: Strand
# Chromosomes to use. Separate by whitespace.
chroms: chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22

# Window around each site for normalizing to 1 (-5000 5000 bp for typical TFBS WGS analysis)
norm_window: -5000 5000
# Range of fragment lengths to be used for analysis. 100 to 200 captures nucleosome sized fragments. 15 to 500 also okay.
size_range: 100 500
# Minimum mapping quality to keep a read.
map_quality: 5

# How many sites to analyze. Use NA/none to analyze all sites.
number_of_sites: none
# Column to use for sorting sites. Use none if analyzing all sites.
sort_by: none
# Whether to sort sites in ascending order (False if you want to keep sites with a large value in the sort_by column).
# Use NA/none to analyze all sites.
ascending: none

# Window around each site to save to outputs.
save_window: -1000 1000
# Range of positions used to calculate the central coverage feature.
center_window: -30 30
fft_window: -960 960
fft_index: 10
# Approximately the fragment length.
smoothing_length: 165

# Bed files containing regions to exclude.
encode_exclude: ../../../resources/Griffin_LR/encode_unified_GRCh38_exclusion_list.bed
centromeres: ../../../resources/Griffin_LR/hg38_centromeres.bed
gaps: ../../../resources/Griffin_LR/hg38_gaps.bed
patches: ../../../resources/Griffin_LR/hg38_fix_patches.bed
alternative_haplotypes: ../../../resources/Griffin_LR/hg38_alternative_haplotypes.bed

step: 15

CNA_normalization: False
individual: False
smoothing: True

exclude_zero_mappability: True
exclude_outliers: True

```

**Comment by egenomics** [comment]
I now see, re-reading the results part in the github that I am missing the 
```
site_lists:
 TssA:
 Quies:
```
I have added the TssA and Quies:
```
# List of paths to the sites of interest files.
site_lists:
  TssA: /playground/soft/ITSFASTR/resources/Griffin_LR/TssA_open.high_mapability.txt
  Quies: /playground/soft/ITSFASTR/resources/Griffin_LR/Quies_closed.high_mapability.txt

```
In site lists a bed file is expected?


I try again with the downloaded files and I obtain the following error, perhaps because site list is empty...:

```
raceback (most recent call last):
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "../../scripts/5_Griffin_LR/griffin_merge_sites.py", line 537, in merge_sites
    mappability_values = fetch_bw_values(mappability_bw,current_sites,site_name,'mappabilty')
  File "../../scripts/5_Griffin_LR/griffin_merge_sites.py", line 341, in fetch_bw_values
    bw = pyBigWig.open(bw_path)
RuntimeError: Received an error during file opening!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../scripts/5_Griffin_LR/griffin_merge_sites.py", line 612, in <module>
    results = p.map(merge_sites, to_do_list, 1) #Send only one interval to each processor at a time.
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: Received an error during file opening!

real	0m27,096s
user	0m42,133s
sys	0m5,142s
[Mon Apr 22 16:05:00 2024]
Error in rule merge_sites:
    jobid: 1
    input: /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/TL163_S35_L001/tmp_bigWig/TL163_S35_L001.uncorrected.bw, /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/TL163_S35_L001/tmp_bigWig/TL163_S35_L001.GC_corrected.bw
    output: /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR/TL163_S35_L001/TL163_S35_L001.uncorrected.coverage.tsv, /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR/TL163_S35_L001/TL163_S35_L001.GC_corrected.coverage.tsv
    conda-env: /playground/soft/ITSFASTR/workflow/rules/5_Griffin_LR/.snakemake/conda/83bdac28aeafad987454fdff386c9581_
    shell:
        
        time ../../scripts/5_Griffin_LR/griffin_merge_sites.py         --sample_name TL163_S35_L001         --uncorrected_bw_path /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/TL163_S35_L001/tmp_bigWig/TL163_S35_L001.uncorrected.bw         --GC_corrected_bw_path /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed/TL163_S35_L001/tmp_bigWig/TL163_S35_L001.GC_corrected.bw         --GC_map_corrected_bw_path none         --mappability_correction False         --tmp_dir /corebm/tmp/cnag_tollagu/test_claret/tmp/testclaret/trimmed         --results_dir /corebm/tmp/cnag_tollagu/test_claret/results/testclaret/trimmed/Griffin_LR         --mappability_bw ../../../resources/Griffin_LR/k100.Umap.MultiTrackMappability.bw         --chrom_sizes_path ../../../resources/Griffin_LR/hg38.standard.chrom.sizes         --sites_yaml ../../../config/config.yaml         --griffin_scripts ../../scripts/5_Griffin_LR         --chrom_column Chrom         --position_column position         --strand_column Strand         --chroms chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22         --norm_window -5000 5000         --save_window -1000 1000         --center_window -30 30         --fft_window -960 960         --fft_index 10         --smoothing_length 165         --exclude_paths ../../../resources/Griffin_LR/encode_unified_GRCh38_exclusion_list.bed ../../../resources/Griffin_LR/hg38_centromeres.bed ../../../resources/Griffin_LR/hg38_gaps.bed ../../../resources/Griffin_LR/hg38_fix_patches.bed ../../../resources/Griffin_LR/hg38_alternative_haplotypes.bed         --step 15         --CNA_normalization False         --individual False         --smoothing True         --exclude_outliers True         --exclude_zero_mappability True         --number_of_sites none         --sort_by none         --ascending none         --CPU 24
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Comment by moldovannorbert** [comment]
Dear @egenomics 
Yes, your guess was correct about missing the `site_lists` files. To highlight their necessity I modified the README by adding this as a step to modifying the config file.
The site files needs to be in the format provided in the example. This is a remnant of the original tool, Griffin. Please see their [documentation](https://github.com/adoebley/Griffin) on how to create these files.

I can't replicate your error unfortunately. After downloading the example site files and adding this to the config as you showed the site_list should be populated with the two options underneath it.
Based on the error you shared there is something wrong with opening the bigWig file of genome wide mappability scores, found in the mappability track file. Did you download this file as instructed in step 9? If so can you try to download it again and tell me if it results in the same error?
